# Generated by Django 2.1.7 on 2019-03-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190314_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count_items',
            field=models.IntegerField(default=0),
        ),
    ]
